server:
  port: 8086

spring:
 kafka:
     consumer:
       group-id: oasis-subscriber
       bootstrap-servers: localhost:9092
       value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


workflow:
  process:
    name: bank_workflow
  messaging:
    topic: bank-trandaction
  error:
    id: OASIS-0002
    message: Error subscribing to Kafka topic ${workflow.messaging.topic}




