server:
  port: 8086

spring:
  data:
    mongodb:
      database: oasis-example
      host: localhost
      port: 27017
  kafka:
    consumer:
      group-id: oasis-subscriber
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: com.springernature.oasis.example.domain

camunda.bpm:
  admin-user:
    id: admin
    password: c4mund4
    firstName: Camunda
    lastName: Admin
  database:
    type: mysql
  filter:
    create: All tasks

workflow:
  process:
    name: OASiSExample
  messaging:
    topic: oasis-example
  error:
    id: OASIS-0002
    message: Error subscribing to Kafka topic ${workflow.messaging.topic}




