spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

swagger:
  service:
    title: account-management-api
    description: account management api
    api:
      version: 1.0.0
      endpoint: /account/*

server:
  port: 8086

account-management:
  transaction:
    topic: bank-transaction
